## Netlify configuration to proxy frontend routes to backend API
## Replace YOUR_BACKEND_URL with your deployed API base URL (e.g., Railway)

# Proxy API under /api/* to your backend
[[redirects]]
  from = "/api/*"
  to = "https://developers-api-gpw9.onrender.com/:splat"
  status = 200
  force = true

# Optional: direct auth routes
[[redirects]]
  from = "/auth/*"
  to = "https://developers-api-gpw9.onrender.com/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/users/*"
  to = "https://developers-api-gpw9.onrender.com/users/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/docs"
  to = "https://developers-api-gpw9.onrender.com/docs"
  status = 200
  force = true